accesing
packages
	 ^ {
		'Trachel'->{'Callbacks'. 'Core'. 'Events'. 'Shapes'. 'ShapesForArrow'. 'Tests'. 'Viva'.}.
		'Roassal2'->{
			'Animation'. 'AttachPoint'. 'AttachPoint-Tests'.
			'Builder-AnimatedScatterPlot'. 'Builder-ApplicationMatrix'. 'Builder-AxisAdapted'.
			'Builder-BoxPlot'. 'Builder-Calendar'.
			'Builder-CircularMap'. 'Builder-Common'.
			'Builder-Composer'. 'Builder-DSM'. 'Builder-Explora'.
			'Builder-Grapher-Core'. 'Builder-Grapher-Decorators'.
			'Builder-Grapher-Decorators-Tests'. 'Builder-Grapher-Labeling'.
			'Builder-Grapher-Obsolete'. 'Builder-Grapher-Tests'.
			'Builder-Kiviat'. 'Builder-Legend'. 
			'Builder-Map'. 'Builder-Map-Tests'. 'Builder-Menu'.
			'Builder-Mondrian'. 'Builder-MondrianOLD'. 'Builder-NameCloud'.
			'Builder-PieChart'. 'Builder-ScatterplotMap'. 
			'Builder-ScrollBar'. 'Builder-SimilarityMatrix'.
			'Builder-Simon'. 'Builder-Spectrograph'. 
			'Builder-StackBarPlot'. 'Builder-StructureMatrix'.
			'Builder-Sunburst'. 'Builder-TextBuilder'.
			'Builder-Timeline'. 'Builder-Timeline-Tests'. 'Builder-TreeMap'.
			'Builder-UI-Slider'. 'Builder-UML'. 
			'Cachetor'. 'ColorNormalizer'.
			'Core'. 'Core-Tests'. 'ExampleBrowser'. 'Experimental'.
			'Exporter-HTML5'. 'Exporter-PNG'. 'Exporter-SVG'. 
			'Interactions'. 'Interactions-Resize'. 'Interactions-Resize-Tests'.
			'Layouts'. 'Layouts-Tests'. 'LineDecorations'. 
			'Scaling'. 'Scaling-Tests'.
			'Selection'. 'Shapes'. 'Sparkline'. 'Table'. 'Tests'. 'Utility'}
		}